<?php


namespace Akademiano\Content\Articles\Model;


use Akademiano\Content\Files\Images\Model\LinkedImagesWorker;

class ArticleImagesWorker extends LinkedImagesWorker
{
    const WORKER_NAME = "articleImagesWorker";
    const TABLE_ID = ArticlesWorker::TABLE_ID + 1;
    const TABLE_NAME = "article_images";

    public static function getEntityClassForMapFilter()
    {
        return ArticleImage::class;
    }

    public function find($criteria, $limit = null, $offset = null, $orderBy = null)
    {
        return parent::find($criteria, $limit, $offset, $orderBy); // TODO: Change the autogenerated stub
    }


}
