language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer global require "fxp/composer-asset-plugin:~1.3"
  - composer self-update
  - composer install --prefer-dist
  - ulimit -c unlimited || true

script:
  - php vendor/bin/codecept run unit  --coverage --coverage-xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
