global_exclude_dirs:
    - vendor
    - tests
    - data
    - public/data
    - public/assets

exclude_patterns:
    - c3.php
    - router.php

pre_composer_script: |
    #!/bin/bash
    composer global require "fxp/composer-asset-plugin:^1.1.1"
